azure_region = "EastUS"
kubernetes_version = "1.12.7"
resource_group = "AksTerraform-test-demo"
acr_name = "aksterraformacrdemo3"
keyvault_rg = "AksTerraform-test-demo"
keyvault_name = "keyvaultdemotest"
